// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/zachpuck/otter-controller/pkg/apis/otters/v1alpha1"
	scheme "github.com/zachpuck/otter-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SeaOttersGetter has a method to return a SeaOtterInterface.
// A group's client should implement this interface.
type SeaOttersGetter interface {
	SeaOtters(namespace string) SeaOtterInterface
}

// SeaOtterInterface has methods to work with SeaOtter resources.
type SeaOtterInterface interface {
	Create(*v1alpha1.SeaOtter) (*v1alpha1.SeaOtter, error)
	Update(*v1alpha1.SeaOtter) (*v1alpha1.SeaOtter, error)
	UpdateStatus(*v1alpha1.SeaOtter) (*v1alpha1.SeaOtter, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SeaOtter, error)
	List(opts v1.ListOptions) (*v1alpha1.SeaOtterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SeaOtter, err error)
	SeaOtterExpansion
}

// seaOtters implements SeaOtterInterface
type seaOtters struct {
	client rest.Interface
	ns     string
}

// newSeaOtters returns a SeaOtters
func newSeaOtters(c *OttersV1alpha1Client, namespace string) *seaOtters {
	return &seaOtters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the seaOtter, and returns the corresponding seaOtter object, and an error if there is any.
func (c *seaOtters) Get(name string, options v1.GetOptions) (result *v1alpha1.SeaOtter, err error) {
	result = &v1alpha1.SeaOtter{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("seaotters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SeaOtters that match those selectors.
func (c *seaOtters) List(opts v1.ListOptions) (result *v1alpha1.SeaOtterList, err error) {
	result = &v1alpha1.SeaOtterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("seaotters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested seaOtters.
func (c *seaOtters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("seaotters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a seaOtter and creates it.  Returns the server's representation of the seaOtter, and an error, if there is any.
func (c *seaOtters) Create(seaOtter *v1alpha1.SeaOtter) (result *v1alpha1.SeaOtter, err error) {
	result = &v1alpha1.SeaOtter{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("seaotters").
		Body(seaOtter).
		Do().
		Into(result)
	return
}

// Update takes the representation of a seaOtter and updates it. Returns the server's representation of the seaOtter, and an error, if there is any.
func (c *seaOtters) Update(seaOtter *v1alpha1.SeaOtter) (result *v1alpha1.SeaOtter, err error) {
	result = &v1alpha1.SeaOtter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("seaotters").
		Name(seaOtter.Name).
		Body(seaOtter).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *seaOtters) UpdateStatus(seaOtter *v1alpha1.SeaOtter) (result *v1alpha1.SeaOtter, err error) {
	result = &v1alpha1.SeaOtter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("seaotters").
		Name(seaOtter.Name).
		SubResource("status").
		Body(seaOtter).
		Do().
		Into(result)
	return
}

// Delete takes name of the seaOtter and deletes it. Returns an error if one occurs.
func (c *seaOtters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("seaotters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *seaOtters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("seaotters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched seaOtter.
func (c *seaOtters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SeaOtter, err error) {
	result = &v1alpha1.SeaOtter{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("seaotters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
