// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// OtterListerExpansion allows custom methods to be added to
// OtterLister.
type OtterListerExpansion interface{}

// OtterNamespaceListerExpansion allows custom methods to be added to
// OtterNamespaceLister.
type OtterNamespaceListerExpansion interface{}
