// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SeaOtterListerExpansion allows custom methods to be added to
// SeaOtterLister.
type SeaOtterListerExpansion interface{}

// SeaOtterNamespaceListerExpansion allows custom methods to be added to
// SeaOtterNamespaceLister.
type SeaOtterNamespaceListerExpansion interface{}
