// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	otters_v1alpha1 "github.com/zachpuck/otter-controller/pkg/apis/otters/v1alpha1"
	versioned "github.com/zachpuck/otter-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/zachpuck/otter-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/zachpuck/otter-controller/pkg/client/listers/otters/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SeaOtterInformer provides access to a shared informer and lister for
// SeaOtters.
type SeaOtterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SeaOtterLister
}

type seaOtterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSeaOtterInformer constructs a new informer for SeaOtter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSeaOtterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSeaOtterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSeaOtterInformer constructs a new informer for SeaOtter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSeaOtterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OttersV1alpha1().SeaOtters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OttersV1alpha1().SeaOtters(namespace).Watch(options)
			},
		},
		&otters_v1alpha1.SeaOtter{},
		resyncPeriod,
		indexers,
	)
}

func (f *seaOtterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSeaOtterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *seaOtterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&otters_v1alpha1.SeaOtter{}, f.defaultInformer)
}

func (f *seaOtterInformer) Lister() v1alpha1.SeaOtterLister {
	return v1alpha1.NewSeaOtterLister(f.Informer().GetIndexer())
}
