// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/zachpuck/otter-controller/pkg/apis/otters/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOtters implements OtterInterface
type FakeOtters struct {
	Fake *FakeOttersV1alpha1
	ns   string
}

var ottersResource = schema.GroupVersionResource{Group: "otters.k8s.dokuforest.com", Version: "v1alpha1", Resource: "otters"}

var ottersKind = schema.GroupVersionKind{Group: "otters.k8s.dokuforest.com", Version: "v1alpha1", Kind: "Otter"}

// Get takes name of the otter, and returns the corresponding otter object, and an error if there is any.
func (c *FakeOtters) Get(name string, options v1.GetOptions) (result *v1alpha1.Otter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ottersResource, c.ns, name), &v1alpha1.Otter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Otter), err
}

// List takes label and field selectors, and returns the list of Otters that match those selectors.
func (c *FakeOtters) List(opts v1.ListOptions) (result *v1alpha1.OtterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ottersResource, ottersKind, c.ns, opts), &v1alpha1.OtterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OtterList{}
	for _, item := range obj.(*v1alpha1.OtterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested otters.
func (c *FakeOtters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ottersResource, c.ns, opts))

}

// Create takes the representation of a otter and creates it.  Returns the server's representation of the otter, and an error, if there is any.
func (c *FakeOtters) Create(otter *v1alpha1.Otter) (result *v1alpha1.Otter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ottersResource, c.ns, otter), &v1alpha1.Otter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Otter), err
}

// Update takes the representation of a otter and updates it. Returns the server's representation of the otter, and an error, if there is any.
func (c *FakeOtters) Update(otter *v1alpha1.Otter) (result *v1alpha1.Otter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ottersResource, c.ns, otter), &v1alpha1.Otter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Otter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOtters) UpdateStatus(otter *v1alpha1.Otter) (*v1alpha1.Otter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ottersResource, "status", c.ns, otter), &v1alpha1.Otter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Otter), err
}

// Delete takes name of the otter and deletes it. Returns an error if one occurs.
func (c *FakeOtters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ottersResource, c.ns, name), &v1alpha1.Otter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOtters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ottersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.OtterList{})
	return err
}

// Patch applies the patch and returns the patched otter.
func (c *FakeOtters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Otter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ottersResource, c.ns, name, data, subresources...), &v1alpha1.Otter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Otter), err
}
