// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/zachpuck/otter-controller/pkg/apis/otters/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSeaOtters implements SeaOtterInterface
type FakeSeaOtters struct {
	Fake *FakeOttersV1alpha1
	ns   string
}

var seaottersResource = schema.GroupVersionResource{Group: "otters.k8s.dokuforest.com", Version: "v1alpha1", Resource: "seaotters"}

var seaottersKind = schema.GroupVersionKind{Group: "otters.k8s.dokuforest.com", Version: "v1alpha1", Kind: "SeaOtter"}

// Get takes name of the seaOtter, and returns the corresponding seaOtter object, and an error if there is any.
func (c *FakeSeaOtters) Get(name string, options v1.GetOptions) (result *v1alpha1.SeaOtter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(seaottersResource, c.ns, name), &v1alpha1.SeaOtter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeaOtter), err
}

// List takes label and field selectors, and returns the list of SeaOtters that match those selectors.
func (c *FakeSeaOtters) List(opts v1.ListOptions) (result *v1alpha1.SeaOtterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(seaottersResource, seaottersKind, c.ns, opts), &v1alpha1.SeaOtterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SeaOtterList{}
	for _, item := range obj.(*v1alpha1.SeaOtterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested seaOtters.
func (c *FakeSeaOtters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(seaottersResource, c.ns, opts))

}

// Create takes the representation of a seaOtter and creates it.  Returns the server's representation of the seaOtter, and an error, if there is any.
func (c *FakeSeaOtters) Create(seaOtter *v1alpha1.SeaOtter) (result *v1alpha1.SeaOtter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(seaottersResource, c.ns, seaOtter), &v1alpha1.SeaOtter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeaOtter), err
}

// Update takes the representation of a seaOtter and updates it. Returns the server's representation of the seaOtter, and an error, if there is any.
func (c *FakeSeaOtters) Update(seaOtter *v1alpha1.SeaOtter) (result *v1alpha1.SeaOtter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(seaottersResource, c.ns, seaOtter), &v1alpha1.SeaOtter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeaOtter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSeaOtters) UpdateStatus(seaOtter *v1alpha1.SeaOtter) (*v1alpha1.SeaOtter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(seaottersResource, "status", c.ns, seaOtter), &v1alpha1.SeaOtter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeaOtter), err
}

// Delete takes name of the seaOtter and deletes it. Returns an error if one occurs.
func (c *FakeSeaOtters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(seaottersResource, c.ns, name), &v1alpha1.SeaOtter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSeaOtters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(seaottersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SeaOtterList{})
	return err
}

// Patch applies the patch and returns the patched seaOtter.
func (c *FakeSeaOtters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SeaOtter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(seaottersResource, c.ns, name, data, subresources...), &v1alpha1.SeaOtter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeaOtter), err
}
