// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/zachpuck/otter-controller/pkg/client/clientset/versioned/typed/otters/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOttersV1alpha1 struct {
	*testing.Fake
}

func (c *FakeOttersV1alpha1) SeaOtters(namespace string) v1alpha1.SeaOtterInterface {
	return &FakeSeaOtters{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOttersV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
